# frozen_string_literal: true

module DiscourseIsthereanydeal
  class DealFormatter
    def self.topic_title(date)
      "Free Games - #{date.strftime('%B %d, %Y')}"
    end

    # Summary opening post listing deal counts per shop.
    def self.format_summary(deals)
      shop_counts = Hash.new(0)
      deals.each do |deal_data|
        shop_name = deal_data.dig("deal", "shop", "name") || "Unknown"
        shop_counts[shop_name] += 1
      end

      lines = []
      lines << "Today's free game deals from [IsThereAnyDeal.com](https://isthereanydeal.com/):\n"
      lines << "| Shop | Deals |"
      lines << "|---|---|"
      shop_counts.sort_by { |_, count| -count }.each do |shop, count|
        lines << "| #{shop} | #{count} |"
      end
      lines << "\nEach deal is posted as a reply below."
      lines << "\n---"
      lines << "*This topic was automatically generated by the IsThereAnyDeal plugin.*"
      lines.join("\n")
    end

    # Formats a single deal for posting as its own reply.
    def self.format_deal_reply(deal_data)
      title = deal_data["title"]
      deal = deal_data["deal"] || {}
      shop_name = deal.dig("shop", "name") || "Unknown"
      url = deal["url"]
      regular_amount = deal.dig("regular", "amount")
      currency = deal.dig("regular", "currency") || ""
      drm = format_drm(deal["drm"])
      expiry = deal["expiry"]

      banner = deal_data.dig("assets", "banner600") ||
               deal_data.dig("assets", "banner300") ||
               deal_data.dig("assets", "banner145")

      lines = []

      type_badge = deal_data["type"] == "dlc" ? " `[DLC]`" : ""
      lines << "## #{title}#{type_badge}\n"

      if banner.is_a?(String) && !banner.empty?
        lines << "![#{title}](#{banner})\n"
      end

      # Price line: ~~regular~~ **Free** until expiry
      price_line = ""
      if regular_amount && regular_amount > 0
        price_line = "~~#{currency} #{format('%.2f', regular_amount)}~~ "
      end
      price_line += "**Free**"

      if expiry.present?
        begin
          expiry_time = Time.parse(expiry.to_s)
          price_line += " until #{expiry_time.strftime('%B %d, %Y at %H:%M UTC')}"
        rescue ArgumentError
          price_line += " until #{expiry}"
        end
      end

      lines << price_line
      lines << ""

      # Shop and DRM info
      info_parts = ["**Shop:** #{shop_name}"]
      info_parts << "**DRM:** #{drm}" if drm.present?
      lines << info_parts.join(" · ")
      lines << ""

      lines << "[Claim this deal](#{url})" if url.present?

      lines.join("\n")
    end

    def self.format_drm(drm)
      return "" if drm.nil?

      Array(drm).map do |d|
        d.is_a?(Hash) ? d["name"] : d.to_s
      end.join(", ")
    end

    private_class_method :format_drm
  end
end
