# frozen_string_literal: true

module DiscourseIsthereanydeal
  class DealFormatter
    # Maps country codes to timezone identifiers
    COUNTRY_TIMEZONES = {
      "EU" => "Europe/Berlin",
      "US" => "America/New_York",
      "GB" => "Europe/London",
      "DE" => "Europe/Berlin",
      "FR" => "Europe/Paris",
      "IT" => "Europe/Rome",
      "ES" => "Europe/Madrid",
      "NL" => "Europe/Amsterdam",
      "PL" => "Europe/Warsaw",
      "SE" => "Europe/Stockholm",
      "NO" => "Europe/Oslo",
      "DK" => "Europe/Copenhagen",
      "FI" => "Europe/Helsinki",
      "PT" => "Europe/Lisbon",
      "AT" => "Europe/Vienna",
      "CH" => "Europe/Zurich",
      "BE" => "Europe/Brussels",
      "AU" => "Australia/Sydney",
      "NZ" => "Pacific/Auckland",
      "CA" => "America/Toronto",
      "BR" => "America/Sao_Paulo",
      "JP" => "Asia/Tokyo",
      "KR" => "Asia/Seoul",
      "CN" => "Asia/Shanghai",
      "IN" => "Asia/Kolkata",
      "RU" => "Europe/Moscow",
    }.freeze

    # Maps timezone identifiers to display abbreviations
    TIMEZONE_ABBREVIATIONS = {
      "Europe/Berlin" => "CET",
      "America/New_York" => "EST",
      "Europe/London" => "GMT",
      "Europe/Paris" => "CET",
      "Europe/Rome" => "CET",
      "Europe/Madrid" => "CET",
      "Europe/Amsterdam" => "CET",
      "Europe/Warsaw" => "CET",
      "Europe/Stockholm" => "CET",
      "Europe/Oslo" => "CET",
      "Europe/Copenhagen" => "CET",
      "Europe/Helsinki" => "EET",
      "Europe/Lisbon" => "WET",
      "Europe/Vienna" => "CET",
      "Europe/Zurich" => "CET",
      "Europe/Brussels" => "CET",
      "Australia/Sydney" => "AEST",
      "Pacific/Auckland" => "NZST",
      "America/Toronto" => "EST",
      "America/Sao_Paulo" => "BRT",
      "Asia/Tokyo" => "JST",
      "Asia/Seoul" => "KST",
      "Asia/Shanghai" => "CST",
      "Asia/Kolkata" => "IST",
      "Europe/Moscow" => "MSK",
    }.freeze

    def self.topic_title(date)
      "IsThereAnyDeal - Free Games for #{date.strftime('%d/%m/%Y')}"
    end

    # Summary opening post listing deal counts per shop.
    def self.format_summary(deals)
      shop_counts = Hash.new(0)
      deals.each do |deal_data|
        shop_name = deal_data.dig("deal", "shop", "name") || "Unknown"
        shop_counts[shop_name] += 1
      end

      lines = []
      lines << "Today's free game deals from [IsThereAnyDeal.com](https://isthereanydeal.com/):\n"
      lines << "| Shop | Deals |"
      lines << "|---|---|"
      shop_counts.sort_by { |_, count| -count }.each do |shop, count|
        lines << "| #{shop} | #{count} |"
      end
      lines << "\nEach deal is posted as a reply below."
      lines << "\n---"
      lines << "*This topic was automatically generated by the IsThereAnyDeal plugin.*"
      lines.join("\n")
    end

    # Formats a single deal for posting as its own reply.
    def self.format_deal_reply(deal_data)
      title = deal_data["title"]
      deal = deal_data["deal"] || {}
      shop_name = deal.dig("shop", "name") || "Unknown"
      url = deal["url"]
      regular_amount = deal.dig("regular", "amount")
      currency = deal.dig("regular", "currency") || ""
      drm = format_drm(deal["drm"])
      expiry = deal["expiry"]

      banner = deal_data.dig("assets", "banner600") ||
               deal_data.dig("assets", "banner300") ||
               deal_data.dig("assets", "banner145")

      lines = []

      type_badge = deal_data["type"] == "dlc" ? " `[DLC]`" : ""
      lines << "## #{title}#{type_badge}\n"

      if banner.is_a?(String) && !banner.empty?
        lines << "![#{title}](#{banner})\n"
      end

      # Table row 1: price and expiry
      price_cell = regular_amount && regular_amount > 0 ? "~~#{currency} #{format('%.2f', regular_amount)}~~" : ""
      free_cell = "**Free**"
      if expiry.present?
        free_cell += " until **#{format_expiry(expiry)}**"
      end

      lines << "| | |"
      lines << "|---|---|"
      lines << "| #{price_cell} | #{free_cell} |"

      # Table row 2: shop and DRM
      drm_cell = drm.present? ? "**DRM:** #{drm}" : ""
      lines << "| **Shop:** #{shop_name} | #{drm_cell} |"

      # Table row 3: claim link spanning both columns
      if url.present?
        lines << "| [Claim this deal](#{url}) | |"
      end

      lines.join("\n")
    end

    def self.format_expiry(expiry)
      country = SiteSetting.isthereanydeal_country
      tz_name = COUNTRY_TIMEZONES[country] || "UTC"
      tz_abbrev = TIMEZONE_ABBREVIATIONS[tz_name] || "UTC"

      utc_time = Time.parse(expiry.to_s).utc
      tz = ActiveSupport::TimeZone[tz_name]
      local_time = tz ? utc_time.in_time_zone(tz) : utc_time

      "#{local_time.strftime('%B %d, %Y at %H:%M')} #{tz_abbrev}"
    rescue ArgumentError
      expiry.to_s
    end

    def self.format_drm(drm)
      return "" if drm.nil?

      Array(drm).map do |d|
        d.is_a?(Hash) ? d["name"] : d.to_s
      end.join(", ")
    end

    private_class_method :format_drm, :format_expiry
  end
end
