# frozen_string_literal: true

module DiscourseIsthereanydeal
  class DealFormatter
    def self.topic_title(date)
      "Free Games - #{date.strftime('%B %d, %Y')}"
    end

    def self.format_topic_body(deals)
      lines = []
      lines << "Here are today's free game deals found on [IsThereAnyDeal.com](https://isthereanydeal.com/):\n"

      deals.each { |deal_data| lines << format_single_deal(deal_data) }

      lines << "\n---"
      lines << "*This topic was automatically generated by the IsThereAnyDeal plugin.*"
      lines.join("\n")
    end

    def self.format_reply_body(deals)
      lines = []
      lines << "Additional free game deals found:\n"

      deals.each { |deal_data| lines << format_single_deal(deal_data) }

      lines.join("\n")
    end

    def self.format_single_deal(deal_data)
      title = deal_data["title"]
      game_type = deal_data["type"]
      deal = deal_data["deal"] || {}
      shop_name = deal.dig("shop", "name") || "Unknown"
      url = deal["url"]
      regular_amount = deal.dig("regular", "amount")
      currency = deal.dig("regular", "currency") || ""
      cut = deal["cut"]
      platforms = format_platforms(deal["platforms"])
      drm = format_drm(deal["drm"])
      expiry = deal["expiry"]

      banner = deal_data.dig("assets", "banner600") ||
               deal_data.dig("assets", "banner300") ||
               deal_data.dig("assets", "banner145")

      lines = []

      if banner.is_a?(String) && !banner.empty?
        lines << "![#{title}](#{banner})"
      end

      type_badge = game_type == "dlc" ? " `[DLC]`" : ""
      lines << "### [#{title}](#{url})#{type_badge}\n"

      lines << "| | |"
      lines << "|---|---|"
      lines << "| **Shop** | #{shop_name} |"

      if regular_amount && regular_amount > 0
        lines << "| **Regular Price** | #{currency} #{format('%.2f', regular_amount)} |"
      end

      lines << "| **Discount** | #{cut}% off |" if cut
      lines << "| **Platforms** | #{platforms} |" if platforms.present?
      lines << "| **DRM** | #{drm} |" if drm.present?

      if expiry.present?
        begin
          expiry_time = Time.parse(expiry.to_s)
          lines << "| **Expires** | #{expiry_time.strftime('%B %d, %Y at %H:%M UTC')} |"
        rescue ArgumentError
          lines << "| **Expires** | #{expiry} |"
        end
      end

      lines << ""
      lines.join("\n")
    end

    def self.format_platforms(platforms)
      return "" if platforms.nil?

      Array(platforms).map do |p|
        p.is_a?(Hash) ? p["name"] : p.to_s
      end.join(", ")
    end

    def self.format_drm(drm)
      return "" if drm.nil?

      Array(drm).map do |d|
        d.is_a?(Hash) ? d["name"] : d.to_s
      end.join(", ")
    end

    private_class_method :format_single_deal, :format_platforms, :format_drm
  end
end
